import type { Metadata } from "next";
import { Geist, Geist_Mono, Quantico } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignUpButton, UserButton, Show } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexProvider";

const quantico = Quantico({
    weight: ["400", "700"],
    variable: "--font-quantico",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${quantico.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <ConvexClientProvider>{children}</ConvexClientProvider>                
                <ClerkProvider>
                    <header className="absolute top-0 left-0 flex justify-start items-center p-4 gap-4 h-16">
                        <Show when="signed-out">
                            <SignInButton />
                            <SignUpButton>
                                <button className="bg-green-300 text-blue-700 rounded-full font-bold">
                                    Sign Up
                                </button>
                            </SignUpButton>
                        </Show>
                        <Show when="signed-in">
                            <UserButton />
                        </Show>
                    </header>
                </ClerkProvider>
            </body>
        </html >
    );
}
